Слои data и domain. | Dagger2 | Room
EpicTeam4/TravelAssistant pull request #1
Opened 2022-09-19 15:15 UTC by EpicTeam4

2022-09-19 19:59 UTC, NLCodeTeam requested changes

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/adapters/CityAdapter.kt
> +            with(cities[position]) {
А если такой позиции нет? упадем?

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/adapters/CityAdapter.kt
> +                val image = ASSETS_FOLDER.plus("$imgName.jpg")
адаптер не должен решать откуда брать нужный путь, он должен приходить вместе с данными, даже если это моки

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/adapters/CityAdapter.kt
> +        private const val ASSETS_FOLDER = "file:///android_asset/"
Делегируй это какому-то другому классу, а не адаптеру и прокидывай внутрь вместе с данными

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/CitiesListFragment.kt
> +        val layoutManager = GridLayoutManager(requireContext(), 2)
цифра 2 должна быть константой с правильным названием того, заем она нужна

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/CitiesListFragment.kt
> +        infoViewModel = ViewModelProvider(this, factory)[InfoViewModel::class.java]
не понял, а мы не можем из даггера получить VM ?

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/CitiesListFragment.kt
> +    private fun onCityClick(id: Long) {
не оставляй пустые методы без реализации, в крайнем случае пиши так //TODO в след пре подъедет такой-то функционал

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/InfoViewModel.kt
> +            _cityLoaded.postValue(useCase.getCities())
Та же самая тема, что и у Альбека - походы в сеть и в БД надо защищить от доступа не из IO диспетчера/треда

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/core/database/dao/CityDAO.kt
> +    fun getAllCities(): List<City>
точно suspend функции тут не нужны?

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/di/Annotations.kt
> +class ViewModelFactory @Inject constructor(
Ну вот же у тебя есть фабрика для DI, через нее и инжекти себе VM-ы

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/domain/entity/City.kt
> +    @ColumnInfo(name = Schema.DESCRIPTION) val description: String? = "",
если у тебя значение по умолчанию пустая строка, то String? тебе не нужен, лишний риск ни к чему

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/domain/repository/InfoRepository.kt
> +    fun getCities(): List<City>
вот тут точно нужен suspend

2022-09-19 19:59 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/domain/usecase/GetInfoUseCase.kt
> +    fun getCities(): List<City>
Интерфейс у юзкейса можно убрать и сделать его классом просто

2022-09-20 07:47 UTC, severstal commented
предлагаю все фичи мержить в девелоп а не мастер

2022-09-20 07:50 UTC, severstal commented
нужен скрипт явной инициализации (заполнения) базы данных

2022-09-20 07:53 UTC, severstal commented on app/src/main/java/com/example/travelassistant/features/travelinfo/domain/repository/InfoRepository.kt
> +    fun getCities(): List<City>
почему интерфейс в домене, а реализация в дате?

2022-09-20 07:54 UTC, severstal commented on app/src/main/java/com/example/travelassistant/features/travelinfo/domain/entity/City.kt
> +    @ColumnInfo(name = Schema.DESCRIPTION) val description: String? = "",
сущности базы должны быть общие, т.е. в коре/датабаза

2022-09-20 08:05 UTC, severstal commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/adapters/CityAdapter.kt
> +                    placeholder(R.drawable.moscow)
просто непонятно - что за блок? почему после загрузки из ассетов R.drawable.moscow ?

2022-09-20 08:07 UTC, severstal commented
коммент (Слои data и domain) коммита не соотв сути

2022-09-20 08:55 UTC, closed without merging

2022-09-20 13:18 UTC, EpicTeam4 commented
.