Переход на MVI и исправление замечаний.
EpicTeam4/TravelAssistant pull request #8
Opened 2022-10-03 19:49 UTC by EpicTeam4

2022-10-06 19:18 UTC, NLCodeTeam requested changes

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/ViewStates.kt
> +sealed class CitiesViewState {
InfoViewState {
 object Loading: InfoViewState()
    data class Error(val errorModel: ErrorModel): InfoViewState()
    data class Content(
    val cities: List<City> = listOf(),
    val ports: List<Port> = listOf(),
    val hotels: List<Hotel> = listOf()
): InfoViewState()
}

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +    private lateinit var hotelsList: ArrayAdapter<Any>
убрать Any

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +
infoViewModel.state.observe(viewLifecycleOwner, ::handleState)

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +    private var selectedHotel = SelectedHotel()
убрать на viewModel

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +                infoViewModel.hotelState.observe(viewLifecycleOwner, ::handleState)
убрать обе строчки и вызывать метод vm куда ты передаешь позицию

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +                    infoViewModel.initHotels(selectedCityId)
название поменять

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +        infoViewModel.hotelState.observe(viewLifecycleOwner, ::handleState)
следить за LV нужно тут и одни раз

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +        hotelsList.notifyDataSetChanged()
убрать, пересоздаешь адаптер и переподкидываешь RV и все

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +        hotelsList.notifyDataSetChanged()
DiffUtils заюзать

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +        fun getBundle(id: Long?): Bundle {
посмотри как через навигацию сделать такое

2022-10-06 19:18 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/ToDestinationFragment.kt
> +        portsList.notifyDataSetChanged()
тоже переделать

2022-10-10 17:44 UTC, NLCodeTeam requested changes

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/core/network/ApiMapper.kt
> +class ApiMapper @Inject constructor(private val clientApi: KudagoClientApi) {
Логическое значение

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/core/network/model/HotelModel.kt
> +    val id: Int = 0,
Оставь только то, что ты используешь

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/CitiesListFragment.kt
> +        requireActivity().toNavigate(viewCommand.pathId)
Потом перенести на ViewModel

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/TravelInfoViewModel.kt
> +    private var _destSelectedPort = MutableLiveData<DestPortSpinnerPosition>().apply { value = DestPortSpinnerPosition() }
Это убрать

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/TravelInfoViewModel.kt
> +            when (val result = useCase.getCities()) {
объединить 2 запроса

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/TravelInfoViewModel.kt
> +    fun init() {
init {

}

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/FromDestinationFragment.kt
> +        if (viewCommand is GoToFragment) goToFragment(viewCommand)
else super.handleCommand() для общего фрагмента

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/FromDestinationFragment.kt
> +        return infoViewModel.selectedPort.value?.pos.orDefault()
убрать все

2022-10-10 17:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +                infoViewModel.dataState.observe(viewLifecycleOwner, ::handleState)
Убрать это

2022-10-11 21:19 UTC, EpicTeam4 commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +
используется в initObservers()

2022-10-11 21:21 UTC, EpicTeam4 commented on app/src/main/java/com/example/travelassistant/features/travelinfo/presentation/ui/destination/HotelFragment.kt
> +                infoViewModel.dataState.observe(viewLifecycleOwner, ::handleState)
тогда не обновляются значения в TextView.

2022-10-13 15:00 UTC, merged